Add publish action, remove repository option

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -9,10 +9,6 @@ inputs:
     description: The path to the mod directory. Defaults to the current directory.
     required: false
     default: ./
-  repository:
-    description: The repository to release to. Defaults to the current repository.
-    required: false
-    default: ${{ github.repository }}
   replace:
     description: Whether or not to replace an existing release. Defaults to false.
     required: false
@@ -26,17 +22,9 @@ inputs:
     required: false
     default: false
   workflow:
-    description: The workflow file in .github/workflows to use for the release. Defaults to the first file running the geode-sdk/build-geode-mod action.
+    description: The workflow file in .github/workflows to use for the release. Defaults to the first file running the build-geode-mod action.
     required: false
     default: ''
-
-outputs:
-  modid:
-    description: The mod ID of the released mod.
-    value: ${{ steps.version.outputs.modid }}
-  version:
-    description: The version of the released mod.
-    value: ${{ steps.version.outputs.version }}
 
 runs:
   using: composite
@@ -55,21 +43,13 @@ runs:
           echo -e "\e[38;2;0;255;0mVersion found"'!'"\e[0m Using version \e[38;2;0;255;255m$VERSION\e[0m"
         fi
         echo version=$VERSION >> $GITHUB_OUTPUT
-        MODID=$(jq -r .id mod.json || true)
-        if [ -z "$MODID" ]; then
-          echo -e "\e[38;2;255;0;0mError:\e[0m No ID found in mod.json"
-          exit 1
-        else
-          echo -e "\e[38;2;0;255;0mID found"'!'"\e[0m Using ID \e[38;2;0;255;255m$MODID\e[0m"
-        fi
-        echo modid=$MODID >> $GITHUB_OUTPUT
 
     - name: Check Existing Release
       if: ${{ inputs.replace == 'false' }}
       id: check
       shell: bash
       run: |
-        RELEASE=$(gh release view v${{ steps.version.outputs.version }} --repo ${{ inputs.repository }} --json tagName || true)
+        RELEASE=$(gh release view v${{ steps.version.outputs.version }} --repo ${{ github.repository }} --json tagName || true)
         if [ -z "$RELEASE" ]; then
           echo -e "\e[38;2;0;255;0mNo releases found!\e[0m"
           echo -e "Creating new release for version \e[38;2;0;255;255m${{ steps.version.outputs.version }}\e[0m..."
@@ -132,12 +112,12 @@ runs:
             echo -e "\e[38;2;255;0;0mError:\e[0m No workflow found running the geode-sdk/build-geode-mod action"
             exit 1
           fi
-          RUNID=$(gh run list --repo ${{ inputs.repository }} --workflow $WORKFLOW --status completed --json event --json databaseId --jq '.[] | select(.event!="pull_request") | .databaseId' | head -n 1 || true)
+          RUNID=$(gh run list --repo ${{ github.repository }} --workflow $WORKFLOW --status completed --json event --json databaseId --jq '.[] | select(.event!="pull_request") | .databaseId' | head -n 1 || true)
         else
-          RUNID=$(gh run list --repo ${{ inputs.repository }} --workflow ${{ inputs.workflow }} --status completed --json event --json databaseId --jq '.[] | select(.event!="pull_request") | .databaseId' | head -n 1 || true)
+          RUNID=$(gh run list --repo ${{ github.repository }} --workflow ${{ inputs.workflow }} --status completed --json event --json databaseId --jq '.[] | select(.event!="pull_request") | .databaseId' | head -n 1 || true)
         fi
         if [ -z "$RUNID" ]; then
-          echo -e "\e[38;2;255;0;0mError:\e[0m No runs found for repository ${{ inputs.repository }}"
+          echo -e "\e[38;2;255;0;0mError:\e[0m No runs found"
           exit 1
         else
           echo -e "\e[38;2;0;255;0mRun found"'!'"\e[0m Using run ID \e[38;2;0;255;255m$RUNID\e[0m"
@@ -154,7 +134,6 @@ runs:
         merge-multiple: true
         path: build-output
         run-id: ${{ steps.runid.outputs.runid }}
-        repository: ${{ inputs.repository }}
 
     - name: Release Version
       id: release
