better error handling

diff --git a/publish/action.yml b/publish/action.yml
--- a/publish/action.yml
+++ b/publish/action.yml
@@ -49,19 +49,21 @@ runs:
           echo -e "\e[38;2;0;255;0mDownload link found"'!'"\e[0m Using link \e[38;2;0;255;255m$DOWNLOAD_LINK\e[0m"
         fi
 
-        curl https://api.geode-sdk.org/v1/mods/$MOD_ID -f
-        if [ $? -ne 0 ]; then
-          curl -X POST https://api.geode-sdk.org/v1/mods -d '{"download_link":"$DOWNLOAD_LINK"}' -H "Content-Type: application/json" -H "Authorization: Bearer $GEODE_TOKEN" -f
-          if [ $? -ne 0 ]; then
-            echo -e "\e[38;2;255;0;0mError:\e[0m Failed to create mod"
+        echo -e "Updating mod \e[38;2;0;255;255m$MOD_ID\e[0m to version \e[38;2;0;255;255m$VERSION\e[0m..."
+        MOD_RESPONSE=$(curl https://api.geode-sdk.org/v1/mods/$MOD_ID | jq -r .error || true)
+        if [ -n "$MOD_RESPONSE" ]; then
+          echo -e "\e[38;2;0;255;0mNo mod found!\e[0m Creating new mod..."
+          MOD_CREATE=$(curl -X POST https://api.geode-sdk.org/v1/mods -d '{"download_link":"$DOWNLOAD_LINK"}' -H "Content-Type: application/json" -H "Authorization: Bearer $GEODE_TOKEN" -f | jq -r .error || true)
+          if [ -n "$MOD_CREATE" ]; then
+            echo -e "\e[38;2;255;0;0mError:\e[0m Failed to create mod: $MOD_CREATE"
             exit 1
           else
             echo -e "\e[38;2;0;255;0mMod created"'!'"\e[0m"
           fi
         fi
 
-        curl -X POST https://api.geode-sdk.org/v1/mods/$MOD_ID/versions -d '{"download_link":"$DOWNLOAD_LINK"}' -H "Content-Type: application/json" -H "Authorization: Bearer $GEODE_TOKEN" -f
-        if [ $? -ne 0 ]; then
+        MOD_UPDATE=$(curl -X POST https://api.geode-sdk.org/v1/mods/$MOD_ID/versions -d '{"download_link":"$DOWNLOAD_LINK"}' -H "Content-Type: application/json" -H "Authorization: Bearer $GEODE_TOKEN" -f | jq -r .error || true)
+        if [ -n "$MOD_UPDATE" ]; then
           echo -e "\e[38;2;255;0;0mError:\e[0m Failed to create version"
           exit 1
         else
